#!/bin/bash

echo "🚀 VIRA - Create Repository & Push"
echo "===================================="
echo ""
echo "Repository 'VIRA' belum ada di GitHub."
echo ""
echo "📋 LANGKAH-LANGKAH:"
echo ""
echo "1. Buka browser dan kunjungi:"
echo "   https://github.com/new"
echo ""
echo "2. Isi form:"
echo "   - Repository name: VIRA"
echo "   - Description: VIRA - AI Assistant for Android with Gemini"
echo "   - Pilih: Public"
echo "   - JANGAN centang 'Add a README file'"
echo "   - JANGAN pilih .gitignore atau license"
echo ""
echo "3. Klik 'Create repository'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Sudah buat repository? Tekan Enter untuk lanjut push..."
echo ""

# Push dengan force (karena repository baru)
echo "📤 Pushing to GitHub..."
git push -u origin main --force

if [ $? -eq 0 ]; then
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "✅ PUSH BERHASIL!"
    echo ""
    echo "🎉 NEXT STEPS:"
    echo ""
    echo "1. Buka repository:"
    echo "   https://github.com/Nobody-Just-Me/VIRA"
    echo ""
    echo "2. Klik tab 'Actions' untuk monitor build"
    echo "   https://github.com/Nobody-Just-Me/VIRA/actions"
    echo ""
    echo "3. Tunggu ~10-15 menit sampai build selesai (✅ hijau)"
    echo ""
    echo "4. Download APK:"
    echo "   - Klik workflow run yang selesai"
    echo "   - Scroll ke 'Artifacts'"
    echo "   - Download 'VIRA-Release-APK'"
    echo ""
    echo "5. Extract ZIP dan install APK di HP Android"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📱 Setelah install:"
    echo "   - Buka aplikasi VIRA"
    echo "   - Tap Settings (⚙️)"
    echo "   - Input Gemini API Key"
    echo "   - Mulai chat!"
    echo ""
    echo "🎊 Selamat! VIRA siap digunakan!"
    echo ""
else
    echo ""
    echo "❌ Push gagal!"
    echo ""
    echo "Kemungkinan masalah:"
    echo "1. Repository belum dibuat"
    echo "2. Credentials salah"
    echo "3. Token tidak punya akses 'repo'"
    echo ""
    echo "Solusi:"
    echo "- Pastikan repository sudah dibuat di GitHub"
    echo "- Gunakan Personal Access Token yang benar"
    echo "- Token harus punya scope 'repo'"
    echo ""
fi
